# Credit to @ Aeroluna for the workflow to build the plugin
name: Build

on:
  push:
    branches: [ "main" ]
    paths:
    - .github/workflows/build.yml
    - Nest.sln

jobs:
  build:
    name: Build
    strategy:
      matrix:
        project-path: [ Nest.csproj ]
        game-version: [ 1.29.1, 1.34.2, 1.37.1, 1.39.1, 1.40.0 ]
    uses: Aeroluna/workflows/.github/workflows/bs-build-version-release.yml@main
    with:
      project-path: ${{ matrix.project-path }}
      game-version: ${{ matrix.game-version }}
      additional-project-paths: '["Nest.csproj"]'
    secrets: inherit